### ISSUE TITLE
Comments from Simon Stevenson

### ISSUE THREAD

**Issue by farr** [kazewong/BackPop#15]
Simon left the following comment on the P&P website: 

> Nice work! We explored the progenitors of the first three gravitational-wave events (including GW150914) in this paper (https://arxiv.org/abs/1704.01352 see Figure 1), with a very early version of what eventually became COMPAS. We used fixed population hyperparameters in that study though. In an earlier draft of that paper we had talked about 'rewinding' binary evolution, but it was edited out for clarity. It's cool to see people developing that idea, and seeing hints of the interesting studies you might be able to do with it in the future!  Another thing worth pointing out is that in COMPAS (https://arxiv.org/abs/2109.10352) the random variables associated with supernova kicks (e.g., magnitudes and angles) are explicitly treated as input parameters, on the same standing as initial masses or orbital periods (as advocated for by Andrews et al. 2018).   Simon

We should 

- [ ] Cite the COMPAS exploration of the first three events (in the intro?)
- [ ] Discuss the COMPAS GW150914 results briefly in our section that currently compares progenitor results from Jeff & us.
- [ ] Note that COMPAS *does* treat the random variables as inputs (that is: it implements a proper mathematical function for the evolution); be sure to cite the above COMPAS paper when we do.

I'll reply to Simon on P&P that we're going to be addressing this comment.

**Comment by kazewong** [comment]
PR merged

**Comment by farr** [comment]
See https://github.com/kazewong/BackPop/pull/17#issuecomment-1148109128

**Comment by katiebreivik** [comment]
I think we discussed this offline -- reopen if necessary!
