### ISSUE TITLE
Zevin's P&P Review

### ISSUE THREAD

**Issue by farr** [kazewong/BackPop#16]
P&P REVIEW  

Is the author list appropriate? 
> Yes.  

Is any data used in any point/form? This includes data from auxiliary channels and "hidden" usage of data for simulations etc.  
> Posterior samples for all GW events in GWTC-3 are used.   

Are there statements of what the LSC will or will not do? (this includes searches and hardware). 
> No.  

Are proper references made to related work within the LSC? 
> Yes.   

Are references to LIGO instruments/results up to date? 
* [ ] At the beginning of Section 3, please cite the GW150914 discovery paper and state which posterior samples are used, citing GWOSC if applicable. 
* [ ] In the middle of Section 3, please indicate which posterior samples are used for GWTC-3 events, citing GWOSC if applicable.
* [ ] Please include the standard acknowledgment when using LIGO data: “This material is based upon work supported by NSF's LIGO Laboratory which is a major facility fully funded by the National Science Foundation.”  

Is there an acknowledgement of computing resources accessed through the LIGO-Virgo Collaboration: Computing acknowledgements 
> Not applicable.   

This article has my approval as P&P reviewer after addressing the minor comments above.   Really cool paper! I’ve attached a marked-up pdf with a number of non-P&P related comments. I also marked typos/grammatical errors when I came across them in the pdf. Please let me know if you have trouble viewing the comments.

[ms_mjz.pdf](https://github.com/kazewong/BackPop/files/8836211/ms_mjz.pdf)

**Comment by katiebreivik** [comment]
Thanks @farr — I’ll take care of both sets of comments (Zevin and Stevenson) tomorrow in the same PR.

**Comment by kazewong** [comment]
PR Merged
